DELETE FROM TBL_ROLES WHERE ROLE_NAME IN ('DEFAULT', 'ADMIN', 'MODERATOR');

SET @NEW_ID = (SELECT NEXT_VAL FROM TBL_ROLES_SEQ);
INSERT INTO TBL_ROLES(ID, CREATED_AT, IS_ACTIVE, UPDATED_AT, UUID, ROLE_NAME)
VALUES (@NEW_ID, SYSDATE(), TRUE, SYSDATE(), UUID(), 'DEFAULT');
UPDATE TBL_ROLES_SEQ SET NEXT_VAL = @NEW_ID + 1;

SET @NEW_ID = (SELECT NEXT_VAL FROM TBL_ROLES_SEQ);
INSERT INTO TBL_ROLES(ID, CREATED_AT, IS_ACTIVE, UPDATED_AT, UUID, ROLE_NAME)
VALUES (@NEW_ID, SYSDATE(), TRUE, SYSDATE(), UUID(), 'ADMIN');
UPDATE TBL_ROLES_SEQ SET NEXT_VAL = @NEW_ID + 1;

SET @NEW_ID = (SELECT NEXT_VAL FROM TBL_ROLES_SEQ);
INSERT INTO TBL_ROLES(ID, CREATED_AT, IS_ACTIVE, UPDATED_AT, UUID, ROLE_NAME)
VALUES (@NEW_ID, SYSDATE(), TRUE, SYSDATE(), UUID(), 'MODERATOR');
UPDATE TBL_ROLES_SEQ SET NEXT_VAL = @NEW_ID + 1;

DELETE FROM TBL_GROUPS WHERE GROUP_NAME IN ('INDIVIDUAL', 'JOINT');

SET @NEW_ID = (SELECT NEXT_VAL FROM TBL_GROUPS_SEQ);
INSERT INTO TBL_GROUPS(ID, CREATED_AT, IS_ACTIVE, UPDATED_AT, UUID, GROUP_NAME)
VALUES (@NEW_ID, SYSDATE(), TRUE, SYSDATE(), UUID(), 'INDIVIDUAL');
UPDATE TBL_GROUPS_SEQ SET NEXT_VAL = @NEW_ID + 1;

SET @NEW_ID = (SELECT NEXT_VAL FROM TBL_GROUPS_SEQ);
INSERT INTO TBL_GROUPS(ID, CREATED_AT, IS_ACTIVE, UPDATED_AT, UUID, GROUP_NAME)
VALUES (@NEW_ID, SYSDATE(), TRUE, SYSDATE(), UUID(), 'JOINT');
UPDATE TBL_GROUPS_SEQ SET NEXT_VAL = @NEW_ID + 1;